(()=>{'use strict';
const KEY='hurrasDarkFantasySheetsV1',CUR='hurrasDarkFantasyCurrentV1',$=x=>document.getElementById(x);
let entries=[];
function all(){try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(data)?data:[]}catch(e){$('status').textContent='Não foi possível ler o armazenamento.';return []}}
function save(data){try{localStorage.setItem(KEY,JSON.stringify(data));return true}catch(e){$('status').textContent='Armazenamento indisponível ou cheio. Exporte um backup.';return false}}
function open(row){localStorage.setItem(CUR,row.id);location.href='ficha-dark-fantasy.html?open='+encodeURIComponent(row.id)}
function element(tag,txt){const e=document.createElement(tag);if(txt!==undefined)e.textContent=String(txt);return e}
function card(item){const a=element('article');a.className='vault-card';const title=element('h2',item.fields?.Nome||'Sem nome');const meta=element('small','Nível '+(item.fields?.Nível||1)+' · '+(item.fields?.Raça||'Raça indefinida')+' · '+(item.fields?.Classe||'Classe indefinida'));const player=element('p','Jogador: '+(item.fields?.Player||'—'));const saved=element('p','Último salvamento: '+(item.updatedAt?new Date(item.updatedAt).toLocaleString('pt-BR'):'Desconhecido'));const buttons=element('div');buttons.className='vault-controls';let b=element('button','Abrir / editar');b.className='btn';b.onclick=()=>open(item);let d=element('button','Duplicar');d.className='btn';d.onclick=()=>{const clone=JSON.parse(JSON.stringify(item));clone.id='df-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);clone.fields.Nome=(clone.fields?.Nome||'Personagem')+' (cópia)';entries.push(clone);if(save(entries))render()};let ex=element('button','Exportar JSON');ex.className='btn';ex.onclick=()=>download([item],(item.fields?.Nome||'personagem')+'.json',false);let del=element('button','Excluir');del.className='btn vault-danger';del.onclick=()=>{if(!confirm('Excluir definitivamente a ficha '+(item.fields?.Nome||'sem nome')+' deste navegador?'))return;entries=entries.filter(x=>x.id!==item.id);if(save(entries)){if(localStorage.getItem(CUR)===item.id)localStorage.removeItem(CUR);render()}};buttons.append(b,d,ex,del);a.append(title,meta,player,saved,buttons);return a}
function render(){entries=all();$('cards').replaceChildren();const q=$('find').value.trim().toLocaleLowerCase('pt-BR');const list=entries.filter(x=>[x.fields?.Nome,x.fields?.Player,x.fields?.Raça,x.fields?.Classe].join(' ').toLocaleLowerCase('pt-BR').includes(q)).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));if(!list.length){const e=element('p',entries.length?'Nenhuma ficha corresponde à busca.':'Você ainda não tem fichas Dark Fantasy salvas.');e.className='vault-empty';$('cards').append(e)}list.forEach(x=>$('cards').append(card(x)));$('status').textContent=list.length+' personagem(ns) de '+entries.length+' no cofre local.'}
function download(data,name,list){const b=new Blob([JSON.stringify(list?{_format:'hurras-dark-vault-v1',sheets:data}:data[0],null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=element('a');a.href=u;a.download=name.replace(/[\\/:*?"<>|]/g,'-');a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('backups').onclick=()=>{if(!entries.length){$('status').textContent='Não há personagens para exportar.';return}download(entries,'hurras-todos-personagens-dark.json',true)};
$('fileImport').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());const rows=d&&d._format==='hurras-dark-vault-v1'?d.sheets:[d];if(!Array.isArray(rows)||!rows.length||rows.some(x=>!x||typeof x.fields!=='object'||typeof x.stats!=='object'||!Array.isArray(x.magic)))throw Error('Backup incompatível');for(const x of rows){let copy=JSON.parse(JSON.stringify(x));copy.id='df-'+Date.now()+'-'+Math.random().toString(36).slice(2,9);copy.updatedAt=new Date().toISOString();entries.push(copy)}if(save(entries))render()}catch(err){$('status').textContent='Não foi possível importar: '+err.message}e.target.value=''};
$('find').addEventListener('input',render);
render();
})();